# Generated by Django 5.2.4 on 2025-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pellets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight_grains', models.IntegerField()),
                ('caliber', models.CharField(choices=[('4.5mm (.177)', '4.5mm (.177)'), ('5.5mm (.22)', '5.5mm (.22)')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('caliber', models.CharField(choices=[('4.5mm (.177)', '4.5mm (.177)'), ('5.5mm (.22)', '5.5mm (.22)')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
