# Generated by Django 5.2.4 on 2025-07-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('is_open', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hotels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel')),
            ],
        ),
    ]
